<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <PackageOutputPath>../Packages</PackageOutputPath>
    <LangVersion>12</LangVersion>
    <Version>1.1.6</Version>
    <PackageId>USBDeviceMonitor.Win</PackageId>
    <Authors>ElvenBless</Authors>
    <Company>ElvenBless</Company>
    <RepositoryUrl>https://github.com/ElvenBless/USBDeviceMonitor.git</RepositoryUrl>
    <ProjectUrl>https://github.com/ElvenBless/USBDeviceMonitor</ProjectUrl>
    <PackageIcon>images/Icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageDescription>Windows USB device monitoring library with drive letter detection support</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images/Icon.png">
      <Pack>True</Pack>
      <PackagePath>images/</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.6" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>

</Project>
